const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=__dirname;
const source=fs.readFileSync(path.join(root,'app.js'),'utf8');
const storage=new Map();
const localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)};
const context=vm.createContext({localStorage,console,setTimeout,clearTimeout,setInterval,clearInterval,crypto:{randomUUID:()=> 'test-uuid'}});
vm.runInContext(fs.readFileSync(path.join(root,'market-screen.js'),'utf8'),context);
vm.runInContext(fs.readFileSync(path.join(root,'signal-engine.js'),'utf8'),context);
vm.runInContext(fs.readFileSync(path.join(root,'engine-core.js'),'utf8'),context);
for(const file of ['trade-sim.js','candle-store.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context);
vm.runInContext(source.slice(0,source.indexOf("document.querySelectorAll('#marketMode")),context);
const run=(code)=>vm.runInContext(code,context);
assert.match(run('simForm()'),/Saisie manuelle/,'simulator remains available when the market API fails');
context.document={querySelectorAll:()=>[],getElementById:()=>null};
run("all=[{id:'FIL-USDT',sym:'FIL',perpId:'FIL-USDT-SWAP',price:1,perpPrice:1}];current=all[0];scenarioLocks[scenarioLockKey('FIL-USDT','rejection')]={id:'favorite-lock',entry:.92,stop:.93,tp1:.9};toggleFavoriteScenario('FIL-USDT','rejection')");
assert.equal(JSON.parse(storage.get('ir_favorites_v1'))['FIL-USDT'].scenarios.rejection,'favorite-lock','a scenario favorite preserves the exact lock');
run("toggleFavoriteScenario('FIL-USDT','rejection')");
assert.equal(JSON.parse(storage.get('ir_favorites_v1'))['FIL-USDT'].scenarios.rejection,undefined,'the same button removes the favorite');
const rejectionLevels={entry:100,stop:105,tp1:95,tp2:90,tp3:85,risk:5,rr:[1,2,3]};
context.testEngine={live:102,shortSetup:true,shortPattern:'rejection',directional:{shortScore:80,longScore:20},shortRejection:rejectionLevels,anchorKey:'1H',triggerKey:'15m',score:70,signals:[],confluences:[]};
assert.equal(run('chooseFreshScenario(testEngine,"rejection")'),'rejection');
assert.equal(run('scenarioLockFromEngine(testEngine,"rejection")?.entry'),100);
assert.equal(run("isListedXperp('FIL-USDT-SWAP')"),false,'a public swap is not assumed available in the account');
context.testXperpInstruments=[{instId:'ALLO-USD_UM_XPERP-310101',ruleType:'xperp',state:'live'},{instId:'ALLO-USDT-SWAP',ruleType:'normal',state:'live'}];
context.testXperpTickers=[{instId:'ALLO-USD_UM_XPERP-310101',last:'0.30',open24h:'0.25',volCcy24h:'5000000',ts:'1'}];
assert.equal(run('xperpUniverse(testXperpInstruments,testXperpTickers).length'),1,'live X-Perps use their own FUTURES universe');
context.testXperpInstruments.push({instId:'ZAMA-USD_UM_XPERP-310101',ruleType:'xperp',state:'live'});context.testXperpTickers.push({instId:'ZAMA-USD_UM_XPERP-310101',last:'0.5',open24h:'0.4',volCcy24h:'2000000',ts:'1'});
assert.equal(run('xperpUniverse(testXperpInstruments,testXperpTickers).length'),2,'public X-Perps beyond ALLO FIL SOL are scanned');
assert.equal(run('xperpUniverse(testXperpInstruments,testXperpTickers)[0].id'),'ALLO-USD_UM_XPERP-310101');
run("all=[{...xperpUniverse(testXperpInstruments,testXperpTickers)[0],analysisCoverage:'complete',marketFresh:true,marketTs:Date.now(),spreadPct:.2,hasLongScenario:true,longScore:80,signalModel:{qualityScore:80,extensionRisk:10},directional:{longScore:80,shortScore:60},scenarioModel:{breakout:{entry:.31,stop:.29,tp1:.33},pullback:{entry:.29,stop:.27,tp1:.32}}}];current=all[0]");
run("Object.assign(all[0].scenarioModel,{instrumentId:all[0].id,live:all[0].price,longSetup:true,directional:{longScore:80,shortScore:60},analysisAt:Date.now(),triggerKey:'5m',F:Object.fromEntries(DECISION_SPECS.map(([tf])=>[tf,{cs:Array(40).fill({}),c:{t:Date.now()-timeframeMs(tf)}}]))})");
assert.equal(run('scenarioCandidates()[0].market'),'perp','ALLO X-Perp is not mislabeled as Spot');
assert.equal(run('scenarioMarket("breakout")'),'perp','a long X-Perp retains its contract market');
context.testMarket={marketFresh:true,marketTs:Date.now(),spreadPct:.2,volUsd:150000};
assert.equal(run('executionCheck(testMarket).ok'),true,'recent liquid market with narrow spread passes preliminary execution check');
context.testMarket.spreadPct=2;
assert.equal(run('executionCheck(testMarket).ok'),false,'wide spread blocks a scenario ranking');
context.testMarket.marketFresh=false;
assert.equal(run('executionCheck(testMarket).ok'),false,'stale ticker blocks a scenario ranking');
context.testBook={ts:String(Date.now()),bids:[['99.9','9']],asks:[['100.1','9']]};
assert.ok(run('bookDepthUsd(testBook,100).bidUsd')>500,'Spot bid depth is converted to quote currency');
assert.ok(run('bookDepthUsd(testBook,100).askUsd')>500,'Spot ask depth is converted to quote currency');
context.testMarket={market:'spot',marketFresh:true,marketTs:Date.now(),spreadPct:.2,volUsd:150000,bookDepth:run('bookDepthUsd(testBook,100)')};
assert.equal(run('executionCheck(testMarket).ok'),true,'a fresh book supports a Spot scenario');
assert.ok(run('RadarMarket.spotImpact(testMarket.bookDepth).roundTripPct')<.3,'estimated small Spot round trip includes both sides of the book');
context.testExpensiveBook={ts:String(Date.now()),bids:[['99','10']],asks:[['101','10']]};
context.testMarket.bookDepth=run('bookDepthUsd(testExpensiveBook,100)');
assert.equal(run('executionCheck(testMarket).ok'),false,'expensive immediate execution blocks the Spot scenario');
context.testMarket.bookDepth=run('bookDepthUsd(testBook,100)');
context.testMarket.bookDepth.bidUsd=10;
assert.equal(run('executionCheck(testMarket).ok'),false,'thin book blocks a Spot scenario');
context.testMarket.bookDepth=run('bookDepthUsd(testBook,100)');context.testMarket.volUsd=900;
assert.equal(run('executionCheck(testMarket).ok'),true,'a small Spot with sufficient depth can pass without minute volume');
context.testMarket={market:'xperp',marketFresh:true,marketTs:Date.now(),spreadPct:.2,volUsd:900};
assert.equal(run('executionCheck(testMarket).ok'),false,'low-volume X-Perp without checked depth stays excluded');
run("all=[{id:'ALLO-USD_UM_XPERP-310101',sym:'ALLO',market:'xperp',perpId:'ALLO-USD_UM_XPERP-310101',perpPrice:.30,price:.30,analysisCoverage:'complete',perpAnalysisCoverage:'complete',hasShortScenario:false,hasLongScenario:false,perpScenarioModel:{shortSetup:true,shortPattern:'rejection'},shortScore:85}]");
assert.equal(run('scenarioCandidates().length'),0,'forming shorts do not appear among realizable scenarios');
context.testSpotPool=Array.from({length:170},(_,i)=>({id:`BIG${i}-USDT`,market:'spot',price:1,volUsd:10000000-i*1000,chg:0,high:1.01,low:.99}));
context.testSpotPool.push({id:'SMALL-USDT',market:'spot',price:1,volUsd:900,chg:0,high:1.01,low:.99});
const fullSpotQueue=run('RadarMarket.spotAnalysisQueue(testSpotPool)');
assert.equal(fullSpotQueue.length,171,'every Spot with usable data reaches the multi-horizon queue');
assert.equal(new Set(fullSpotQueue.map(x=>x.id)).size,171,'each Spot is analyzed exactly once');
assert.ok(fullSpotQueue.some(x=>x.id==='SMALL-USDT'),'a tiny Spot without a one-minute event is included');
run("all=[{id:'FIL-USDT',sym:'FIL',perpId:'FIL-USDT-SWAP',analysisCoverage:'complete',perpAnalysisCoverage:'complete',perpScenarioModel:{shortSetup:true,shortPattern:'rejection'},shortScore:90,hasShortScenario:true,hasLongScenario:false}]");
assert.equal(run('scenarioCandidates().length'),0,'unverified swaps cannot become trade candidates');
const now=Date.now(),barMs=300000;
const bar=(t,o,h,l,c,confirm=1)=>({t,o,h,l,c,v:100,confirm});
const lock={id:'long-1',entry:100,stop:95,tp1:105};
const forming={schema:'IR_LEARNING_V3',id:'long-1',status:'FORMING',createdAt:now-2*barMs,entry:100,stop:95,tp1:105,direction:'long'};
storage.set('ir_learning_journal_v866',JSON.stringify([forming,{schema:'IR_LEARNING_V2',id:'legacy',status:'CLOSED',outcome:{r:3,status:'TP3'}}]));
const put=(k,v)=>{context[k]=v};put('testLock',lock);put('testBar',bar(now-3*barMs,100,110,99,108));
run('journalAdvance(testLock,"long",[testBar],false,300000)');
assert.equal(JSON.parse(storage.get('ir_learning_journal_v866'))[0].status,'FORMING','TP before activation must not count');
put('testBars',[bar(now-3*barMs,99,100,98,99),bar(now-2*barMs,99,101,98,100.5)]);
run('journalAdvance(testLock,"long",testBars,true,300000)');
assert.equal(JSON.parse(storage.get('ir_learning_journal_v866'))[0].status,'ACTIVATED');
put('testBars',[...context.testBars,bar(now-barMs,101,106,94,102)]);
run('journalAdvance(testLock,"long",testBars,false,300000)');
let journal=JSON.parse(storage.get('ir_learning_journal_v866'));
assert.equal(journal[0].outcome.status,'SL','same candle touching TP and SL must choose SL');
assert.equal(journal[0].outcome.source,'CONFIRMED_CANDLE');
assert.equal(run('learningStats().closed'),1,'legacy outcomes are excluded');
const short={id:'short-1',entry:100,stop:105,tp1:95};put('shortLock',short);
journal.push({schema:'IR_LEARNING_V3',id:'short-1',status:'ACTIVATED',activatedBarTs:now-3*barMs,lastProcessedBarTs:now-3*barMs,activatedAt:now-2*barMs,direction:'short'});
storage.set('ir_learning_journal_v866',JSON.stringify(journal));
put('shortBars',[bar(now-2*barMs,100,101,94,96)]);
run('journalAdvance(shortLock,"short",shortBars,false,300000)');
assert.equal(JSON.parse(storage.get('ir_learning_journal_v866'))[2].outcome.status,'TP1');
let records=JSON.parse(storage.get('ir_learning_journal_v866'));
records.push({schema:'IR_LEARNING_V3',id:'cancel-1',status:'FORMING',createdAt:now-2*barMs,entry:100,stop:95,tp1:105});
records.push({schema:'IR_LEARNING_V3',id:'gap-1',status:'ACTIVATED',activatedBarTs:now-5*barMs,lastProcessedBarTs:now-5*barMs,activatedAt:now-4*barMs});
storage.set('ir_learning_journal_v866',JSON.stringify(records));
put('cancelLock',{id:'cancel-1',entry:100,stop:95,tp1:105});put('gapLock',{id:'gap-1',entry:100,stop:95,tp1:105});
put('cancelBars',[bar(now-2*barMs,99,101,94,100.5)]);
run('journalAdvance(cancelLock,"long",cancelBars,true,300000)');
put('gapBars',[bar(now-barMs,101,105,98,104)]);
run('journalAdvance(gapLock,"long",gapBars,false,300000)');
records=JSON.parse(storage.get('ir_learning_journal_v866'));
assert.equal(records[3].status,'UNVERIFIED','same-bar entry and stop cannot establish order before activation (D04)');
assert.equal(records[4].status,'UNVERIFIED','missing candles cannot create an outcome');
const history=[0,1,2,3,4,5].map(i=>[i*1000,0,0,0,0,0,0,0,1]);put('testHistory',history);
assert.equal(run('btSlice(testHistory,4000,2,1000).map(x=>x[0]).join(",")'),'2000,3000','use latest fully closed history, not the forming bar');
const future=(bars)=>bars.map((b,i)=>[i,0,b[0],b[1],0,0,0,0,1]);
put('future',future([[99,97],[101,99],[104,94],[105,92]]));
put('setup',{entry:100,stop:104,tp1:95});
assert.equal(run('btOutcome(future,0,"rejection",setup,3).hit'),'SL','SHORT rejection is evaluated as short');
put('future',future([[99,97],[99,96],[99,95]]));
assert.equal(run('btOutcome(future,0,"rejection",setup,2).hit'),'NO_ENTRY');
put('future',future([[99,97],[101,99],[102,94],[101,93]]));
assert.equal(run('btOutcome(future,0,"rejection",setup,3).hit'),'TP1');
context.testCosts=[{outcome:'TP1',rr1:2,riskPct:1,score:70},{outcome:'SL',rr1:2,riskPct:1,score:70}];
assert.equal(run('btScoreResult(testCosts).grossR'),.5,'gross expectancy uses risk/reward rather than only win rate');
assert.ok(Math.abs(run('btScoreResult(testCosts).afterLowCostsR')-.3)<1e-9,'hypothetical round-trip costs reduce expectancy in R');
assert.equal(run('nullableNumber(null)'),null);
assert.equal(run('pct(null)'),'N/D');
assert.equal(run('money(null)'),'N/D');
assert.equal(run('rankingCalibrationLab().ok'),true);
assert.equal(run('shortEngineLab().ok'),run('shortEngineLab().total'),'synthetic cases exercise actual short engine');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.equal((html.match(/<script /g)||[]).length,6);
assert.match(html,/<script src="\.\/market-screen\.js\?v=8\.9\.15"><\/script>/);
assert.match(html,/<script src="\.\/engine-core\.js\?v=8\.9\.15"><\/script>/);
assert.match(html,/<script src="\.\/app\.js\?v=8\.9\.15"><\/script>/);
assert.match(fs.readFileSync(path.join(root,'sw.js'),'utf8'),/'\.\/app\.js\?v=8\.9\.15'/);
assert.match(html,/<details class="panel homeFold" id="marketExplorer">/);
assert.match(html,/<details class="panel homeFold" id="radarHelp">/);
class MockSocket{
  constructor(url){this.url=url;this.readyState=1;MockSocket.latest=this}
  send(message){this.lastSent=message}
  close(){this.closed=true}
}
put('WebSocket',MockSocket);
run('testStreamBars=[];testStreamStates=[];testStream=subscribeCandleStream("BTC-USDT","1m",c=>testStreamBars.push(c),s=>testStreamStates.push(s))');
assert.match(MockSocket.latest.url,/\/business$/);
MockSocket.latest.onopen();
assert.match(MockSocket.latest.lastSent,/"channel":"candle1m"/);
MockSocket.latest.onmessage({data:JSON.stringify({arg:{instId:'BTC-USDT',channel:'candle1m'},data:[[String(now),'100','101','99','100.5','10','0','1000','0']]})});
assert.equal(run('testStreamBars.length'),1,'live candle reaches the chart model');
assert.equal(run('testStreamBars[0].c'),100.5);
run('testStream.stop()');
assert.equal(MockSocket.latest.closed,true,'leaving a chart closes its stream');
console.log('checks passed: journal, historical replay, missing data, ranking and single source');
const elements=new Map();
context.document={getElementById:id=>{if(!elements.has(id))elements.set(id,{textContent:'',innerHTML:'',value:id==='tier'?'all':id==='sort'?'score':'',disabled:false});return elements.get(id)},querySelectorAll:()=>[]};
const ticker=(name)=>({instId:name+'-USDT',last:'100',open24h:'98',volCcy24h:'1000000',high24h:'102',low24h:'95',bidPx:'99.9',askPx:'100.1',ts:String(Date.now())});
put('spotRows',[ticker('BTC'),ticker('ETH')]);
put('marketRequests',[]);run('get=async path=>{marketRequests.push(path);return path.includes("instType=SPOT")?spotRows:[]}');
put('mockBars',Array.from({length:120},(_,i)=>({t:i*60000,o:80+i*.1,h:81+i*.1,l:79+i*.1,c:80.5+i*.1,v:10000,confirm:1})));
run('candles=async (id,bar)=>{if(id==="ETH-USDT"&&bar==="30m")throw Error("mock timeframe unavailable");return mockBars.map((c,i)=>({...c,t:i*timeframeMs(bar)}))}');
run('scan()').then(()=>{
  assert.equal(run('all.length'),2,'market universe remains visible');
  assert.equal(run('all.find(x=>x.sym==="ETH").analysisCoverage'),'partial');
  assert.equal(run('all.find(x=>x.sym==="BTC").analysisCoverage'),'complete');
  assert.equal(run('all.find(x=>x.sym==="BTC").marketFresh'),true,'ticker refreshed at scan end');
  assert.equal(run('marketRequests.filter(path=>path.includes("bar=1m")).length'),0,'scan never fetches minute candles');
  assert.match(elements.get('status').textContent,/incomplètes/);
  console.log('scan check: complete, partial and fresh prices');
  put('spotRows',Array.from({length:101},(_,i)=>ticker('ASSET'+i)));
  run('candles=async (id,bar)=>mockBars.map((c,i)=>({...c,t:i*timeframeMs(bar)}))');
  return run('scan()').then(()=>{
    assert.equal(run('all.length'),101);
    assert.equal(run('all[100].analysisCoverage'),'complete','asset after previous top-100 limit is analyzed');
    console.log('universe check: asset 101 receives full analysis');
    put('spotRows',Array.from({length:170},(_,i)=>ticker('COIN'+i)));
    return run('scan()').then(()=>{
      assert.equal(run('all.length'),170,'every Spot remains visible');
      assert.equal(run('all.find(x=>x.sym==="COIN169").analysisCoverage'),'complete','market after the old top-150 cutoff receives full analysis');
      assert.match(elements.get('discovery').innerHTML,/multi-horizons/,'watchlist is based on the same multi-horizon engine');
      console.log('coverage check: all 170 Spot receive full multi-horizon analysis');
    context.document.querySelectorAll=()=>[];
    run('current={...all[0],perpId:"ALLO-USD_UM_XPERP-310101"};get=async path=>{lastFundingPath=path;return [{fundingTime:String(Date.now()-3600000),fundingRate:"0.0001"},{fundingTime:String(Date.now()),fundingRate:"0.0002"}]}');
    return run('metricPage("Funding")').then(()=>{
      assert.match(run('lastFundingPath'),/ALLO-USD_UM_XPERP-310101/,'funding history uses exact contract');
      run('current={...current,perpId:null}');
      return run('metricPage("Funding")').then(()=>{
        assert.match(elements.get('deepBody').innerHTML,/Pas de contrat perpétuel associé/);
        console.log('instrument check: exact X-Perp and Spot-only state');
      });
    });
    });
  });
}).catch(e=>{console.error(e);process.exitCode=1});
