const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(root,'app.js'),'utf8');
const storage=new Map();
const localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)};
const context=vm.createContext({localStorage,console,setTimeout,clearTimeout,crypto:{randomUUID:()=> 'test-uuid'}});
vm.runInContext(source.slice(0,source.indexOf("document.querySelectorAll('#marketMode")),context);
const run=(code)=>vm.runInContext(code,context);
const now=Date.now(),barMs=300000;
const bar=(t,o,h,l,c,confirm=1)=>({t,o,h,l,c,v:100,confirm});
const lock={id:'long-1',entry:100,stop:95,tp1:105};
const forming={schema:'IR_LEARNING_V3',id:'long-1',status:'FORMING',createdAt:now-2*barMs,entry:100,stop:95,tp1:105,direction:'long'};
storage.set('ir_learning_journal_v866',JSON.stringify([forming,{schema:'IR_LEARNING_V2',id:'legacy',status:'CLOSED',outcome:{r:3,status:'TP3'}}]));
const put=(k,v)=>{context[k]=v};put('testLock',lock);put('testBar',bar(now-3*barMs,100,110,99,108));
run('journalAdvance(testLock,"long",[testBar],false,300000)');
assert.equal(JSON.parse(storage.get('ir_learning_journal_v866'))[0].status,'FORMING','TP before activation must not count');
put('testBars',[bar(now-3*barMs,99,100,98,99),bar(now-2*barMs,99,101,98,100.5)]);
run('journalAdvance(testLock,"long",testBars,true,300000)');
assert.equal(JSON.parse(storage.get('ir_learning_journal_v866'))[0].status,'ACTIVATED');
put('testBars',[...context.testBars,bar(now-barMs,101,106,94,102)]);
run('journalAdvance(testLock,"long",testBars,false,300000)');
let journal=JSON.parse(storage.get('ir_learning_journal_v866'));
assert.equal(journal[0].outcome.status,'SL','same candle touching TP and SL must choose SL');
assert.equal(journal[0].outcome.source,'CONFIRMED_CANDLE');
assert.equal(run('learningStats().closed'),1,'legacy outcomes are excluded');
const short={id:'short-1',entry:100,stop:105,tp1:95};put('shortLock',short);
journal.push({schema:'IR_LEARNING_V3',id:'short-1',status:'ACTIVATED',activatedBarTs:now-3*barMs,lastProcessedBarTs:now-3*barMs,activatedAt:now-2*barMs,direction:'short'});
storage.set('ir_learning_journal_v866',JSON.stringify(journal));
put('shortBars',[bar(now-2*barMs,100,101,94,96)]);
run('journalAdvance(shortLock,"short",shortBars,false,300000)');
assert.equal(JSON.parse(storage.get('ir_learning_journal_v866'))[2].outcome.status,'TP1');
let records=JSON.parse(storage.get('ir_learning_journal_v866'));
records.push({schema:'IR_LEARNING_V3',id:'cancel-1',status:'FORMING',createdAt:now-2*barMs,entry:100,stop:95,tp1:105});
records.push({schema:'IR_LEARNING_V3',id:'gap-1',status:'ACTIVATED',activatedBarTs:now-5*barMs,lastProcessedBarTs:now-5*barMs,activatedAt:now-4*barMs});
storage.set('ir_learning_journal_v866',JSON.stringify(records));
put('cancelLock',{id:'cancel-1',entry:100,stop:95,tp1:105});put('gapLock',{id:'gap-1',entry:100,stop:95,tp1:105});
put('cancelBars',[bar(now-2*barMs,99,101,94,100.5)]);
run('journalAdvance(cancelLock,"long",cancelBars,true,300000)');
put('gapBars',[bar(now-barMs,101,105,98,104)]);
run('journalAdvance(gapLock,"long",gapBars,false,300000)');
records=JSON.parse(storage.get('ir_learning_journal_v866'));
assert.equal(records[3].status,'CANCELLED','stop touched before entry cancels observation');
assert.equal(records[4].status,'UNVERIFIED','missing candles cannot create an outcome');
const history=[0,1,2,3,4,5].map(i=>[i*1000,0,0,0,0,0,0,0,1]);put('testHistory',history);
assert.equal(run('btSlice(testHistory,4000,2).map(x=>x[0]).join(",")'),'3000,4000','use latest available history');
const future=(bars)=>bars.map((b,i)=>[i,0,b[0],b[1],0,0,0,0,1]);
put('future',future([[99,97],[101,99],[104,94],[105,92]]));
put('setup',{entry:100,stop:104,tp1:95});
assert.equal(run('btOutcome(future,0,"rejection",setup,3).hit'),'SL','SHORT rejection is evaluated as short');
put('future',future([[99,97],[99,96],[99,95]]));
assert.equal(run('btOutcome(future,0,"rejection",setup,2).hit'),'NO_ENTRY');
put('future',future([[99,97],[101,99],[102,94],[101,93]]));
assert.equal(run('btOutcome(future,0,"rejection",setup,3).hit'),'TP1');
assert.equal(run('nullableNumber(null)'),null);
assert.equal(run('pct(null)'),'N/D');
assert.equal(run('money(null)'),'N/D');
assert.equal(run('rankingCalibrationLab().ok'),true);
assert.equal(run('shortEngineLab().ok'),run('shortEngineLab().total'),'synthetic cases exercise actual short engine');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.equal((html.match(/<script/g)||[]).length,1);
assert.match(html,/<script src="\.\/app\.js"><\/script>/);
assert.match(fs.readFileSync(path.join(root,'sw.js'),'utf8'),/'\.\/app\.js'/);
console.log('checks passed: journal, historical replay, missing data, ranking and single source');
const elements=new Map();
context.document={getElementById:id=>{if(!elements.has(id))elements.set(id,{textContent:'',innerHTML:'',value:id==='tier'?'all':id==='sort'?'score':'',disabled:false});return elements.get(id)},querySelectorAll:()=>[]};
const ticker=(name)=>({instId:name+'-USDT',last:'100',open24h:'98',volCcy24h:'1000000',high24h:'102',low24h:'95',ts:String(now)});
put('spotRows',[ticker('BTC'),ticker('ETH')]);
put('swapRows',[{instId:'BTC-USDT-SWAP'},{instId:'ETH-USDT-SWAP'}]);
run('get=async path=>path.includes("instType=SPOT")?spotRows:path.includes("instType=SWAP")&&path.includes("tickers")?swapRows:path.includes("open-interest")?[{oiUsd:"5000000"}]:path.includes("funding-rate")?[{fundingRate:"0.0001"}]:[]');
put('mockBars',Array.from({length:120},(_,i)=>({t:i*60000,o:80+i*.1,h:81+i*.1,l:79+i*.1,c:80.5+i*.1,v:10000,confirm:1})));
run('candles=async (id,bar)=>{if(id==="ETH-USDT"&&bar==="30m")throw Error("mock timeframe unavailable");return mockBars}');
run('scan()').then(()=>{
  assert.equal(run('all.length'),2,'market universe remains visible');
  assert.equal(run('all.find(x=>x.sym==="ETH").analysisCoverage'),'partial');
  assert.equal(run('all.find(x=>x.sym==="BTC").analysisCoverage'),'complete');
  assert.match(elements.get('market').innerHTML,/BTC/);
  assert.match(elements.get('market').innerHTML,/ETH/);
  assert.match(elements.get('status').textContent,/incomplets/);
  console.log('scan check: complete asset and partial asset both visible');
  put('spotRows',[{...ticker('BTC'),last:'82'}]);put('swapRows',[{instId:'BTC-USDT-SWAP',last:'118'}]);
  put('bearBars',Array.from({length:180},(_,i)=>({t:i*60000,o:100-i*.1,h:101-i*.1,l:99-i*.1,c:100.15-i*.1,v:10000+i*30,confirm:1})));
  put('bullBars',Array.from({length:180},(_,i)=>({t:i*60000,o:100+i*.1,h:101+i*.1,l:99+i*.1,c:100.15+i*.1,v:10000+i*30,confirm:1})));
  run('candles=async id=>id.endsWith("-SWAP")?bullBars:bearBars');
  return run('scan()').then(()=>{
    assert.ok(run('all[0].scenarioModel.shortPattern'),'Spot bearish candidate is detected');
    assert.equal(run('all[0].hasShortScenario'),false,'bullish Perp must veto Spot bearish SHORT');
    console.log('instrument check: SHORT needs Perp confirmation');
    put('swapRows',[{instId:'BTC-USDT-SWAP',last:'82'}]);
    run('candles=async ()=>bearBars');
    return run('scan()').then(()=>{
      assert.ok(run('all[0].perpScenarioModel?.shortPattern'),'Perp bearish pattern is evaluated');
      assert.ok(run('all[0].shortScore>=62'),'Perp direction feeds SHORT score');
      console.log('instrument check: Perp bearish configuration reaches directional gate');
      put('spotRows',Array.from({length:101},(_,i)=>ticker('ASSET'+i)));
      put('swapRows',[]);
      run('candles=async ()=>mockBars');
      return run('scan()').then(()=>{
        assert.equal(run('all.length'),101);
        assert.equal(run('all[100].analysisCoverage'),'complete','asset after the previous top-100 limit is analyzed');
        console.log('universe check: asset 101 receives complete technical analysis');
        context.document.querySelectorAll=()=>[];
        run('current={...all[0],perpId:"ASSET0-USDT-SWAP"};get=async path=>{lastFundingPath=path;return [{fundingTime:String(Date.now()-3600000),fundingRate:"0.0001"},{fundingTime:String(Date.now()),fundingRate:"0.0002"}]}');
        return run('metricPage("Funding")').then(()=>{
          assert.match(run('lastFundingPath'),/instId=ASSET0-USDT-SWAP/,'funding history must use the Perp instrument');
          run('current={...current,perpId:null}');
          return run('metricPage("Funding")').then(()=>{
            assert.match(elements.get('deepBody').innerHTML,/Pas de contrat perpétuel associé/);
            console.log('funding check: Perp identifier and clear Spot-only state');
          });
        });
      });
    });
  });
}).catch(e=>{console.error(e);process.exitCode=1});
