/* On-demand movement explorer. Public data only; selection changes require a click. */
(function(root){
 'use strict';
 const M=root.RadarMovement,key='ir_movement_checks_v1',cache=new Map(),seen=new Set();let lastReport=null;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString('fr-FR',{maximumFractionDigits:d}):'N/D';
 const spreadText=v=>Number.isFinite(v)?(v>0&&v<.0001?'< 0,0001 %':fmt(v,4)+' %'):'N/D';
 const pct=v=>Number.isFinite(v)?fmt(v)+' %':'N/D';
 const date=t=>new Date(t).toLocaleString('fr-FR',{timeZone:'Europe/Paris',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})+' · Paris';
 const volume=v=>Number.isFinite(v)?v.toLocaleString('fr-FR',{notation:'compact',maximumFractionDigits:2})+' USD':'N/D';
 function ledger(){try{const x=JSON.parse(root.localStorage.getItem(key)||'{}');return x&&typeof x==='object'&&!Array.isArray(x)?x:{}}catch{return {}}}
 function record(report){
  const observations=ledger(),reference=report.rows.find(x=>x.sym==='NEAR')?.asset?.id;
  for(const row of report.rows)if(row.asset&&row.comparison){row.observation=M.observe(observations[row.asset.id],{asOf:report.asOf,candidateId:row.asset.id,referenceId:reference,comparison:row.comparison});observations[row.asset.id]=row.observation}
  const bounded=Object.fromEntries(Object.entries(observations).sort((a,b)=>(b[1]?.lastAt||0)-(a[1]?.lastAt||0)).slice(0,100));
  try{root.localStorage.setItem(key,JSON.stringify(bounded));report.saved=true}catch{report.saved=false}
 }
 function method(){return `<details class="movementMethod"><summary>Comment lire ces mesures ?</summary><p>Quatre fenêtres communes se terminent à la dernière heure pleine : 15 min sur 24 h / 7 jours, 1 h sur 7 / 30 jours. Seules les bougies clôturées et les séries complètes sont comparées. Les fenêtres se recouvrent : ce ne sont pas quatre validations indépendantes.</p><p><b>Amplitude :</b> médiane du True Range rapporté à la clôture précédente, en %. <b>Mèches :</b> part moyenne des mèches dans l’étendue des bougies. <b>Directionnalité :</b> déplacement net divisé par le chemin total des clôtures. Un chiffre élevé décrit une direction persistante ; il ne signifie pas « meilleur trade ».</p><p><b>Swings :</b> jambes entre extrema de clôture, confirmées par un retournement d’au moins 1 %. Première et dernière jambes incomplètes exclues. Fréquence par jour, amplitude et durée médianes ; régularité = 1 − dispersion absolue médiane / amplitude médiane, bornée de 0 à 100 %, disponible à partir de 4 jambes.</p><p><b>Ressemblance :</b> indice descriptif, pas le score du moteur ni une probabilité de gain. Dans chaque fenêtre : 25 % amplitude, 25 % fréquence des swings, 25 % mèches, 25 % directionnalité ; moyenne des 4 fenêtres. « Proximité » nécessite au moins 80/100 au total et 70/100 dans chaque fenêtre. Ces seuils sont exploratoires, sans calibration de rentabilité. L’amplitude/durée/régularité des swings restent des détails descriptifs hors indice.</p><p><b>Persistance :</b> « Retrouvée à deux dates » demande deux lectures proches séparées d’au moins 24 h, sans échec observé entre elles ni intervalle de plus de 7 jours entre lectures, avec le même contrat NEAR. Une seule observation reste à confirmer. Les relevés dépendent de tes lancements manuels, sur cet appareil.</p><p><b>Coûts :</b> spread de la cotation actuelle, datée et âgée de 120 s maximum au calcul. Le volume moyen/jour provient des volumes en devise de cotation des bougies. Profondeur, frais de ton compte, glissement et financement ne sont pas mesurés ici.</p><p><b>Exploration :</b> 5 nouveaux contrats au plus par lot, par volume 24 h indicatif décroissant (volume de base × dernier prix). Ce préfiltre n’est pas une recherche exhaustive de ressemblance. Aucun ajout automatique et aucun scan profond des autres marchés. Budget maximal : 3 lectures catalogue/cotations (dont une actualisation finale), puis 16 lectures d’historique par actif, hors relances réseau (3 tentatives maximum par lecture).</p><a href="https://www.okx.com/docs-v5/en/#order-book-trading-market-data-get-candlesticks-history" target="_blank" rel="noopener noreferrer">Source : API publique OKX</a></details>`}
 function details(row,report){
  const observation=row.observation,persistence=observation?.confirmed?'Retrouvée à deux dates espacées d’au moins 24 h':row.comparison?.close?'Proximité observée une fois — à revoir dans 24 h':'Proximité non confirmée';
  return `<details class="movementDetail"><summary>${esc(row.sym)} · mesures et écarts</summary><p>${esc(row.asset?.id||row.reason)}</p>${row.sym!=='NEAR'?`<p>${persistence}. ${report.saved?'Relevé local enregistré.':'Le relevé ne sera pas conservé : stockage indisponible.'}</p>`:''}${row.seriesErrors?.length?`<p class="warn">${row.seriesErrors.map(esc).join('<br>')}</p>`:''}${M.windows.map(w=>{const a=row.profile?.windows[w.key],d=row.comparison?.details.find(x=>x.key===w.key);return `<div class="movementWindow"><b>${w.label}</b><p>${a?.ok?`${esc(a.regime)} · variation ${pct(a.returnPct)} · ${a.swingCount} swings complets ; amplitude médiane ${pct(a.swingPct)}, durée ${fmt(a.swingHours)} h ; régularité ${a.regularity==null?'N/D (moins de 4 swings)':pct(a.regularity*100)}.`:`${fmt(a?.coverage||0,1)} % de couverture · ${esc(a?.reason||row.reason||'Données indisponibles.')}`}</p>${d?.score!=null?`<p>Ressemblance ${fmt(d.score,0)}/100 · amplitude ${fmt(d.amplitudeRatio)} × NEAR · fréquence ${fmt(d.swingDelta)} swing/j d’écart · mèches ${fmt(d.wickDelta)} points d’écart · directionnalité ${fmt(d.efficiencyDelta)} points d’écart.</p>`:''}</div>`}).join('')}<p class="foot">Fenêtres historiques arrêtées au ${date(report.asOf)}. Cotation : ${row.execution?.quoteAt?date(row.execution.quoteAt):'N/D'} ; le spread affiché correspond à ce relevé, pas au prix d’exécution futur.</p></details>`;
 }
 function mount(host,hooks){
  let disposed=false,job=null,report=lastReport,windowKey='15m-1d',message='',progress=null,adding=false;
  function draw(){
   if(disposed)return;const selected=hooks.selected(),busy=!!job||adding;
   host.innerHTML=`<section class="panel movementPanel"><span class="eyebrow">NEAR & SEMBLABLES · COMPARAISON</span><h2>Le même genre de mouvement ?</h2><p class="sub">Comparer amplitude, rythme et bruit sur plusieurs périodes. Indice descriptif de ressemblance, sans validation de rentabilité. Les entrées LONG/SHORT restent évaluées par le moteur du Radar.</p><div class="movementActions"><button class="btn" data-movement="selected" ${busy?'disabled':''}>Comparer ma sélection (${selected.length})</button><button class="btn secondary" data-movement="discover" ${busy?'disabled':''}>Explorer 5 nouveaux candidats</button>${job?'<button class="smallbtn" data-movement="cancel">Arrêter</button>':''}<button class="smallbtn" data-movement="reset" ${busy||!seen.size?'disabled':''}>Recommencer l’exploration</button></div><p class="sub">À la demande · ${seen.size} candidats explorés dans cette session. Les résultats n’ajoutent aucun actif automatiquement.</p><div class="movementStatus" role="status" aria-live="polite">${esc(message||'Lance la comparaison pour mesurer NEAR et les actifs suivis.')}${progress?`<br>${progress.current?esc(progress.current)+' · ':''}${progress.rows.length}/${progress.targetCount||'?'} profils · ${progress.requests}/${progress.maxRequests} lectures maximum` :''}</div>${report?`<p class="sub">Relevé du ${date(report.finishedAt)} · fenêtres arrêtées au ${date(report.asOf)} · ${report.requests} lectures, ${report.cacheHits} séries réutilisées. ${report.saved?'':'Relevé non conservé (stockage indisponible).'} ${report.executionError?'Spread indisponible : '+esc(report.executionError)+'.':''} ${report.mode==='discover'?`${report.rows.length-1} nouveaux candidats sur ${report.remaining} restants dans ce catalogue.`:''}</p><div class="movementTabs" role="group" aria-label="Fenêtre de comparaison">${M.windows.map(w=>`<button class="smallbtn" data-window="${w.key}" aria-pressed="${windowKey===w.key}">${w.label}</button>`).join('')}</div>${table(report,windowKey,selected,busy)}${report.rows.map(row=>details(row,report)).join('')}`:''}${method()}</section>`;
  }
  function table(report,key,selected,busy){
   const rows=[...report.rows].sort((a,b)=>a.sym==='NEAR'?-1:b.sym==='NEAR'?1:(b.comparison?.score??-1)-(a.comparison?.score??-1));
   return `<p class="sub">Sur mobile, fais glisser le tableau ↔. N/D reste visible lorsqu’une mesure manque. Contrats publics : disponibilité dans ton compte à vérifier.</p><div class="movementTableWrap" role="region" tabindex="0" aria-label="Tableau comparatif des profils"><table class="movementTable"><caption>${M.windows.find(w=>w.key===key).label} · ressemblance calculée sur les 4 fenêtres</caption><thead><tr><th scope="col">Actif</th><th scope="col">Ressemblance</th><th scope="col">Amplitude médiane</th><th scope="col">Swings ≥ 1 % / jour</th><th scope="col">Mèches</th><th scope="col">Directionnalité</th><th scope="col">Volume moyen/j</th><th scope="col">Spread du relevé</th></tr></thead><tbody>${rows.map(row=>{const m=row.profile?.windows[key],c=row.comparison,spread=row.execution?.spreadPct;return `<tr data-movement-symbol="${esc(row.sym)}"><th scope="row"><b>${esc(row.sym)}</b><small>${row.sym==='NEAR'?'Référence':selected.includes(row.sym)?'Suivi':'Candidat'}</small>${row.asset&&!selected.includes(row.sym)?`<button class="smallbtn" data-add="${esc(row.asset.id)}" ${busy||!c?.complete||selected.length>=15?'disabled':''}>Ajouter au Radar</button>`:''}</th><td>${row.sym==='NEAR'?'Référence':c?.complete?`<b>${fmt(c.score,0)}/100</b><small>${esc(c.label)}</small>`:'N/D · comparaison partielle'}${!row.asset?`<small>${esc(row.reason)}</small>`:''}</td><td>${m?.ok?pct(m.trPct):'N/D'}</td><td>${m?.ok?fmt(m.swingsPerDay):'N/D'}</td><td>${m?.ok&&m.wickShare!=null?pct(m.wickShare*100):'N/D'}</td><td>${m?.ok?pct(m.efficiency*100):'N/D'}</td><td>${m?.ok?volume(m.volumePerDay):'N/D'}</td><td>${spreadText(spread)}${spread!=null&&m?.ok&&m.trPct>0?`<small>${pct(spread/m.trPct*100)} de l’amplitude</small>`:''}</td></tr>`}).join('')}</tbody></table></div>`;
  }
  async function run(mode){
   if(job||adding)return;if(!hooks.canRun()){message='Un scan est en cours. Relance la comparaison après sa fin.';draw();return}
   job={cancelled:false};const active=job;hooks.setBusy(true);message='Chargement des contrats et des fenêtres communes…';report=null;progress=null;draw();
   try{
    const result=await M.collect({get:hooks.get,decode:hooks.decode,resolve:hooks.resolve,selected:hooks.selected(),mode,seen:[...seen],job:active,cache,onProgress:p=>{progress=p;draw()}});
    if(disposed||active.cancelled)return;record(result);report=result;lastReport=result;
    if(mode==='discover')for(const row of result.rows)if(row.sym!=='NEAR'&&row.asset)seen.add(row.asset.id);
    message='Comparaison terminée. Consulte les écarts et les données manquantes avant d’ajouter un candidat.';
   }catch(e){message=e.cancelled?'Recherche arrêtée ; aucune sélection modifiée.':'Comparaison indisponible : '+e.message}
   finally{job=null;progress=null;hooks.setBusy(false);draw()}
  }
  host.onclick=async e=>{
   const button=e.target.closest?.('button');if(!button||button.disabled)return;
   if(button.dataset.window){windowKey=button.dataset.window;draw();return}
   const action=button.dataset.movement;
   if(action==='selected'||action==='discover'){void run(action);return}
   if(action==='cancel'){if(job)job.cancelled=true;message='Arrêt demandé ; la lecture en cours se termine.';draw();return}
   if(action==='reset'){seen.clear();message='Exploration réinitialisée. Aucun actif suivi n’a été retiré.';draw();return}
   if(button.dataset.add){const row=report?.rows.find(x=>x.asset?.id===button.dataset.add);if(!row?.comparison?.complete||job||adding)return;adding=true;draw();try{await hooks.add(row.sym);message=row.sym+' ajouté à la sélection du Radar.'}catch(e){message=e.message}finally{adding=false;draw()}}
  };
  draw();return {dispose(){disposed=true;if(job)job.cancelled=true;host.onclick=null}};
 }
 root.RadarMovementPanel={mount,key};
})(globalThis);
