const {test}=require('node:test'),assert=require('node:assert/strict');const {env,frames,plain}=require('./harness.cjs');
function seed(e){e.ctx.bars=frames(0)['1H'];e.run("current={id:'T-USDT',sym:'T',market:'spot',price:100,score:60,tier:['small','Petite']};all=[current]");e.ctx.candles=async()=>e.ctx.bars;e.ctx.subscribeCandleStream=()=>({stop(){}})}
test('F18: volume page preserves quote volume and does not multiply by price',async()=>{const e=env();seed(e);let values;e.ctx.lineSvg=v=>{values=v;return ''};await e.run("metricPage('Volume')");assert.equal(values[0],e.ctx.bars[0].v)});
test('F22: late scenario response cannot replace another page for the same asset',async()=>{const e=env();seed(e);let resolve;e.ctx.scenarioHtml=()=>new Promise(r=>resolve=r);await e.run("openDeep(current.id,'scenario')");e.run("toolPage('learn')");const before=e.node('deepBody').innerHTML;resolve('LATE SCENARIO');await new Promise(r=>setImmediate(r));assert.equal(e.node('deepBody').innerHTML,before)});
test('F22: leaving during initial projection prevents a zombie timer',async()=>{const e=env();seed(e);let resolve;e.ctx.renderScenarioMonitor=()=>new Promise(r=>resolve=r);const pending=e.run("openScenarioMonitor(current.id,'breakout')");e.run('backHome()');resolve();await pending;assert.equal(e.timers.size,0)});
test('F22: detail response/timer cannot survive leaving the page',async()=>{const e=env();seed(e);let resolve,first=true;e.ctx.candles=()=>first?(first=false,new Promise(r=>resolve=r)):Promise.resolve(e.ctx.bars);const pending=e.run('openDetail(current.id)');e.run('backHome()');const before=e.node('detailBody').innerHTML;resolve(e.ctx.bars);await pending;assert.equal(e.node('detailBody').innerHTML,before);assert.equal(e.timers.size,0)});
test('F22: metric response cannot replace settings after navigation',async()=>{const e=env();seed(e);let resolve;e.ctx.candles=()=>new Promise(r=>resolve=r);const pending=e.run("openDeep(current.id,'metric','Volume')");e.run("toolPage('settings')");const before=e.node('deepBody').innerHTML;resolve(e.ctx.bars);await pending;assert.equal(e.node('deepBody').innerHTML,before)});
test('F30: clearing local scan history clears memory and disk together',()=>{const e=env();e.run("history={'T-USDT':{samples:[{price:100}]}};localStorage.setItem(STORAGE.scan,JSON.stringify(history));clearScanHistory()");assert.equal(e.store.has('ir_scan_history_v866'),false);assert.deepEqual(plain(e.run('history')),{});e.run('localStorage.setItem(STORAGE.scan,JSON.stringify(history))');assert.equal(e.store.get('ir_scan_history_v866'),'{}')});
test('F32: derived spread/direction match final short boost, scores unchanged',()=>{const e=env();e.ctx.f=frames(-.1);const model=e.run("adaptiveEngine(f,{price:f['5m'].at(-2).c,perpId:'T-USD_UM_XPERP-310101'})");const d=model.directional;assert.equal(d.spread,Math.abs(d.longScore-d.shortScore));assert.equal(d.strongest,d.longScore>d.shortScore?'long':d.shortScore>d.longScore?'short':'neutral')});
test('F26: a delisted favorite contract is not reopened as a live projection',async()=>{const e=env();seed(e);const id='T-USD_UM_XPERP-310101';e.ctx.id=id;e.run("favorites[id]={asset:{id,perpId:id,market:'xperp',sym:'T'},scenarios:{breakdown:'saved'}};scenarioLocks[scenarioLockKey(id,'breakdown')]={id:'saved',market:'perp',entry:100,stop:105,tp1:95}");let opened=false;e.ctx.openScenarioMonitor=async()=>{opened=true};e.ctx.get=async p=>p.includes('/instruments')?[{instId:id,ruleType:'xperp',state:'suspend'}]:[{last:'100'}];await e.run("openFavorite(id,'breakdown')");assert.equal(opened,false);assert.match(e.node('deepBody').innerHTML,/indisponible|non vérifié/i)});
test('F24: old favorite retains its own levels when latest lock is replaced',()=>{const e=env({'ir_learning_journal_v866':JSON.stringify([{id:'old',entry:100,stop:95,tp1:105,status:'CLOSED'}])});e.run("favorites={'T-USDT':{asset:{id:'T-USDT',sym:'T'},scenarios:{breakout:'old'}}};scenarioLocks['T-USDT::breakout']={id:'new',entry:200,stop:190,tp1:210};renderFavorites()");assert.ok(e.node('favoritesBody').innerHTML.includes('100,00'));assert.ok(!e.node('favoritesBody').innerHTML.includes('200,00'))});
test('F25: ticker failure never advertises LIVE; successful recent ticker is labelled',async()=>{const e=env();seed(e);e.ctx.f=frames(0);e.ctx.candles=async(id,bar)=>e.ctx.f[bar];e.run("scenarioMonitorFrames=f;scenarioMonitorKind='breakout';scenarioLocks['T-USDT::breakout']={id:'lock',kind:'breakout',direction:'long',entry:105,stop:95,tp1:110,tp2:115,tp3:120,triggerKey:'15m',anchorKey:'1H'};bindScenarioSim=()=>{}");e.ctx.get=async()=>{throw Error('offline')};await e.run("renderScenarioMonitor('breakout',false)");assert.ok(e.node('deepBody').innerHTML.includes('Prix non actualisé'));assert.ok(!e.node('deepBody').innerHTML.includes('🟢 LIVE'));e.ctx.get=async()=>[{last:'100',ts:String(Date.now())}];await e.run("renderScenarioMonitor('breakout',false)");assert.ok(e.node('deepBody').innerHTML.includes('🟢 Prix actualisé'))});
