const {test}=require('node:test'),assert=require('node:assert/strict');
const {env,frames}=require('./harness.cjs');
const ms=300000,now=1700000000000;
test('F03: all Learning summaries exclude legacy and null R consistently',()=>{const {run}=env({'ir_learning_journal_v866':JSON.stringify([{schema:'IR_LEARNING_V2',id:'old',direction:'long',status:'CLOSED',outcome:{status:'TP3',r:3}},{schema:'IR_LEARNING_V3',id:'null',direction:'short',status:'CLOSED',outcome:{r:null}},{schema:'IR_LEARNING_V3',id:'ok',provenance:{type:'local'},direction:'short',status:'CLOSED',activatedAt:123,outcome:{source:'CONFIRMED_CANDLE',status:'SL',r:-1}}])});assert.equal(run('learningStats().closed'),1);assert.equal(run('learningProposal().sample'),1);assert.equal(run('learningProposal().long.n'),0);assert.equal(run('learningProposal().short.avgR'),-1)});
test('F05: internal gaps are UNVERIFIED; future closed flags cannot resolve observations',()=>{const {ctx,run,store}=env();ctx.lock={id:'x',entry:100,stop:95,tp1:105};const record={id:'x',status:'ACTIVATED',activatedAt:now-4*ms,activatedBarTs:now-5*ms,lastProcessedBarTs:now-5*ms};store.set('ir_learning_journal_v866',JSON.stringify([record]));ctx.bars=[{t:now-5*ms,h:101,l:99,confirm:1},{t:now-ms,h:106,l:99,confirm:1}];assert.equal(run(`journalAdvance(lock,'long',bars,false,${ms},${now}).status`),'UNVERIFIED');store.set('ir_learning_journal_v866',JSON.stringify([{...record,activatedBarTs:now-ms,lastProcessedBarTs:now-ms}]));ctx.bars=[{t:now,h:106,l:99,confirm:1}];assert.equal(run(`journalAdvance(lock,'long',bars,false,${ms},${now}).status`),'ACTIVATED')});
test('F12: levels must be positive and targets ordered; current valid long/short unchanged',()=>{const {run}=env();assert.equal(run("scenarioValid('breakdown',{entry:1,stop:1.1,tp1:-1,tp2:50,tp3:100},1.05)"),false);assert.equal(run("scenarioValid('breakout',{entry:100,stop:95,tp1:105,tp2:103,tp3:110},99)"),false);assert.equal(run("scenarioValid('breakdown',{entry:100,stop:105,tp1:95,tp2:90,tp3:85},102)"),true);assert.equal(run("scenarioValid('breakout',{entry:100,stop:95,tp1:105,tp2:110,tp3:115},99)"),true)});
test('F02: a daily candle is unavailable until its close, including boundary',()=>{const {ctx,run}=env();ctx.rows=[[0,1,9,1,8,1,1,10,1]];assert.equal(run('btSlice(rows,3600000,140,86400000).length'),0);assert.equal(run('btSlice(rows,86400000,140,86400000).length'),1)});
test('F01/F02/F31: complete historical UI path supplies normalized, causal bars and resolves rejection levels',async()=>{const {ctx,run,node}=env();let calls=0,outcomes=0;const start=1700006400000,hour=3600000;
 ctx.historyCandles=async(id,tf)=>{const duration={'1D':24*hour,'4H':4*hour,'1H':hour,'30m':hour/2,'15m':hour/4,'5m':hour/12}[tf];return Array.from({length:tf==='1H'?220:300},(_,i)=>{const t=start+i*duration;return [t,100,102,98,100.5,10,10,1000,1]}).reverse()};
 ctx.inspectFrames=(f)=>{calls++;for(const [tf,bars] of Object.entries(f))for(const c of bars){assert.equal(Array.isArray(c),false);assert.ok(Number.isFinite(c.c));assert.ok(Number.isFinite(c.t))}return {live:102,score:70,shortSetup:true,shortPattern:'rejection',directional:{shortScore:80,longScore:20},regime:{key:'range'},shortRejection:{entry:100,stop:105,tp1:95,tp2:90,tp3:85}}};
 run('adaptiveEngine=inspectFrames');ctx.inspectOutcome=(base,i,kind,sc,horizon)=>{outcomes++;assert.equal(kind,'rejection');assert.equal(sc.entry,100);const boundary=i<154?154:i<198?198:220;assert.ok(i+horizon<boundary);return {hit:'NO_ENTRY',mfe:0,mae:0}};run('btOutcome=inspectOutcome');await run('runWalkForwardLab()');assert.ok(calls>0);assert.equal(outcomes,calls);assert.doesNotMatch(node('btOut').innerHTML,/Laboratoire interrompu/);
});
test('F06: REST refresh wins over old cached candle; newer concurrent WS still wins',async()=>{const {ctx,run,node}=env();ctx.bars=frames(0)['1H'];run("current={id:'T-USDT',sym:'T',market:'spot',price:100};all=[current];bindScenarioSim=()=>{}");let receive;ctx.subscribeCandleStream=(id,tf,fn)=>{receive=fn;return {stop(){}}};ctx.candles=async()=>ctx.bars.map(c=>({...c}));await run('graphPage()');ctx.bars.at(-1).c=101;await node('graphRefresh').onclick();assert.match(node('garea').innerHTML,/Prix bougie 101,00/);let release;ctx.candles=()=>new Promise(r=>release=r);const pending=node('graphRefresh').onclick();receive({...ctx.bars.at(-1),c:103});release(ctx.bars.map(c=>({...c})));await pending;assert.match(node('garea').innerHTML,/Prix bougie 103,00/);run('stopGraphUpdates()')});

test('F01: raw API histories really reach finite adaptive levels through the adapter',()=>{const {ctx,run}=env();const f=frames(.1);ctx.raw=Object.fromEntries(Object.entries(f).map(([k,bars])=>[k,bars.map(c=>[c.t,c.o,c.h,c.l,c.c,1,1,c.v,1])]));const e=run(`(()=>{const normalized=Object.fromEntries(Object.entries(raw).map(([tf,rows])=>[tf,RadarCandles.decode(btSlice(rows,1800000000000,140,timeframeMs(tf)))]));return adaptiveEngine(normalized,{price:117,perpId:'T-USD_UM_XPERP-310101'})})()`);assert.ok(Number.isFinite(e.breakout.entry));assert.ok(Number.isFinite(e.shortRejection.stop))});
