const {test}=require('node:test'),assert=require('node:assert/strict');
const {env,frames,plain}=require('./harness.cjs');
function characterize(){const {ctx,run}=env();return [-.1,0,.1].flatMap(slope=>[1,1e-7].map(scale=>{ctx.f=frames(slope,scale);ctx.x={id:'FIXTURE-USD_UM_XPERP-310101',perpId:'FIXTURE-USD_UM_XPERP-310101',market:'xperp',price:ctx.f['5m'].at(-2).c,chg:slope*10,vol:1e6,medVol:1e6};return plain(run(`(()=>{const e=adaptiveEngine(f,x);return {score:e.score,long:e.directional.longScore,short:e.directional.shortScore,longSetup:e.longSetup,shortSetup:e.shortSetup,regime:e.regime,anchor:e.anchorKey,trigger:e.triggerKey,breakout:e.breakout,pullback:e.pullback,breakdown:e.breakdown,rejection:e.shortRejection}})()`))}))}
test('V8.9.15 reference plus individually reviewed D01/D02 deltas',()=>{
 const expected=structuredClone(require('./fixtures/v8915-models.json')).map(x=>({...x,score:Math.min(100,x.score+12)}));
 for(const fixture of require('./fixtures/d02-reviewed-deltas.json'))for(const d of fixture.changes){const keys=d.path.split('.'),key=keys.pop();let obj=expected[fixture.case];for(const k of keys)obj=obj[k];assert.equal(obj[key],d.before);obj[key]=d.after}
 assert.deepEqual(characterize(),expected);
});
test('D02: forming candle is display-only, unlike the characterized V8.9.15 behavior',()=>{const {ctx,run}=env();ctx.f=frames(.1);const a=plain(run("timeframeFeatures(f['5m'])"));Object.assign(ctx.f['5m'].at(-1),{c:1,l:1});const b=plain(run("timeframeFeatures(f['5m'])"));assert.deepEqual(a,b)});
test('V8.9.15: terminal TP1 and no expiry remain characterized, not silently redesigned',()=>{const {ctx,run,store}=env();const ms=300000,now=1700000000000;ctx.lock={id:'x',entry:100,stop:95,tp1:105};ctx.bars=[{t:now-ms,o:100,h:106,l:99,c:105,confirm:1}];store.set('ir_learning_journal_v866',JSON.stringify([{id:'x',status:'ACTIVATED',activatedBarTs:now-2*ms,lastProcessedBarTs:now-2*ms,activatedAt:now-ms}]));assert.equal(run(`journalAdvance(lock,'long',bars,false,${ms},${now}).outcome.status`),'TP1');ctx.bars.push({t:now,o:105,h:120,l:90,c:100,confirm:1});assert.equal(run(`journalAdvance(lock,'long',bars,false,${ms},${now+ms}).outcome.status`),'TP1');store.set('ir_learning_journal_v866',JSON.stringify([{id:'x',status:'FORMING',createdAt:now-180*86400000}]));ctx.bars=[];assert.equal(run(`journalAdvance(lock,'long',bars,false,${ms},${now}).status`),'FORMING')});
test('synthetic lab never writes production weights or local observations',()=>{const {run,store}=env();const before=run('JSON.stringify(REGIME_WEIGHTS)');run('runGovernedLab()');assert.equal(run('JSON.stringify(REGIME_WEIGHTS)'),before);assert.equal(store.size,0)});
module.exports={characterize};
