// Optional end-to-end gate. Requires Playwright and a Chromium executable.
// node tests/browser-audit.cjs <baseline-directory> <chromium-executable> <artifacts-directory>
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const [baseline,executablePath,output]=process.argv.slice(2);if(!baseline||!executablePath||!output)throw Error('Three paths required');fs.mkdirSync(output,{recursive:true});
const current=path.resolve(__dirname,'..'),errors=[],results=[];
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),parts=u.pathname.split('/'),root=parts[1]==='baseline'?baseline:current;const file=path.join(root,parts.slice(2).join('/')||'index.html');try{res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath,headless:true,args:JSON.parse(process.env.RADAR_CHROMIUM_ARGS||'["--no-sandbox","--disable-dev-shm-usage"]')});const context=await browser.newContext({hasTouch:true,serviceWorkers:'block'});try{
async function open(version,width){const page=await context.newPage();await page.setViewportSize({width,height:844});page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('https://www.okx.com/**',r=>r.fulfill({json:{code:'0',data:[]}}));await page.goto(`http://127.0.0.1:${server.address().port}/${version}/`);await page.waitForFunction(()=>!scanRunning);await page.evaluate(()=>{document.getElementById('clock').textContent='12:00:00';document.getElementById('status').textContent='Scan de référence';});await page.addStyleTag({content:'*{animation:none!important;transition:none!important}'});return page}
for(const width of [360,390,768,1440]){const a=await open('baseline',width),b=await open('current',width);await a.screenshot({path:path.join(output,`baseline-home-${width}.png`)});await b.screenshot({path:path.join(output,`current-home-${width}.png`)});const style=async p=>p.locator('body').evaluate(el=>({background:getComputedStyle(el).backgroundColor,font:getComputedStyle(el).fontFamily}));assert.deepEqual(await style(a),await style(b));results.push({test:'visual identity',width,style:await style(b)});await a.close();await b.close()}
const page=await open('current',390);await page.evaluate(()=>{current={id:'T-USDT',sym:'T',market:'spot',price:100,score:70,tier:['small','Petite'],analysisCoverage:'complete'};all=[current];auditBars=Array.from({length:180},(_,i)=>({t:1700000000000+i*3600000,o:100,h:102,l:98,c:100,v:1000,confirm:i===179?0:1}));candles=async()=>auditBars.map(c=>({...c}));subscribeCandleStream=()=>({stop(){}})});await page.evaluate(()=>openDeep(current.id,'graph'));const last=()=>page.locator('#garea svg').evaluate(el=>JSON.parse(el.dataset.candles).at(-1).c);assert.equal(await last(),100);await page.evaluate(()=>auditBars.at(-1).c=101);await page.locator('#graphRefresh').click();assert.equal(await last(),101);await page.locator('#garea .candleHit').nth(50).dispatchEvent('pointerdown');assert.ok(await page.locator('#garea .chartTooltip.show').isVisible());assert.match(await page.locator('#garea .chartTooltip').innerText(),/High 102,00/);assert.equal(await page.locator('#garea .chartSelection circle').count(),2);results.push({test:'selected candle uses SVG-local data and visible High/Low markers'});await page.screenshot({path:path.join(output,'current-graph-390.png'),fullPage:true});results.push({test:'real graph REST refresh',before:100,after:101});
await page.locator('#sim_entry').fill('100');await page.locator('#sim_stop').fill('95');await page.locator('#sim_tp1').fill('110');await page.locator('#sim_capital').fill('500');await page.locator('#sim_leverage').fill('1');assert.ok(await page.locator('.simResults').isVisible());const before=await page.locator('#sim_entry').inputValue();await page.locator('#graphRefresh').click();assert.equal(await page.locator('#sim_entry').inputValue(),before);results.push({test:'graph simulator survives refresh'});
await page.evaluate(()=>toolPage('settings'));assert.equal(await page.getByText('Mode compact / détaillé',{exact:false}).count(),0);await page.evaluate(()=>toolPage('learn'));assert.equal(await page.locator('#deepBody .click').count(),0);await page.evaluate(()=>{history['T-USDT']={samples:[{price:100}]};localStorage.setItem(STORAGE.scan,JSON.stringify(history));toolPage('settings')});await page.getByText("Effacer l'historique local des scans",{exact:false}).click();assert.equal(await page.evaluate(()=>Object.keys(history).length),0);assert.equal(await page.evaluate(()=>localStorage.getItem(STORAGE.scan)),null);results.push({test:'settings and history removal'});
// D05-D08: use actual scenario UI and storage with deterministic six-horizon market data.
await page.evaluate(()=>{
 const now=Date.now(),id='T-USD_UM_XPERP-310101';
 auditFrames=Object.fromEntries(DECISION_SPECS.map(([tf,n])=>{const ms=timeframeMs(tf),end=Math.floor(now/ms)*ms;return [tf,Array.from({length:180},(_,i)=>{const p=100+.1*i+Math.sin(i/8)*.4;return {t:end-(179-i)*ms,o:p,h:p+1,l:p-1,c:p+.15,v:10000+i*30,confirm:i===179?0:1}})]}));
 current={id,perpId:id,sym:'T',market:'xperp',price:auditFrames['5m'].at(-2).c,vol:1e6,volUsd:1e6,medVol:1e6,marketTs:now,marketFresh:true,spreadPct:.1,analysisCoverage:'complete',tier:['small','Petite']};all=[current];
 candles=async(id,tf,n)=>auditFrames[tf].slice(-n);get=async path=>path.includes('/instruments')?[{instId:id,ruleType:'xperp',state:'live'}]:[{last:String(current.price),bidPx:String(current.price*.9995),askPx:String(current.price*1.0005),ts:String(Date.now())}];
 current.scenarioModel=candidateModel(auditFrames,current);current.directional=current.scenarioModel.directional;
});
await page.evaluate(()=>openDetail(current.id,'perp','long','breakout'));await page.evaluate(()=>openDeep(current.id,'scenario'));
await page.getByText('Ouvrir la projection en temps réel',{exact:false}).click();await page.waitForFunction(()=>!!document.querySelector('.monitorHero'));
const locked=await page.evaluate(()=>JSON.stringify(scenarioLocks[scenarioLockKey(current.id,'breakout')]));
await page.evaluate(async()=>{scenarioMonitorAnalysisAt=Date.now()-3*timeframeMs('5m');await renderScenarioMonitor('breakout',false)});
assert.match(await page.locator('.monitorHero').innerText(),/DÉCISION SUSPENDUE/);
await page.getByRole('button',{name:'Actualiser les six horizons'}).click();await page.waitForFunction(()=>!document.querySelector('.monitorHero')?.textContent.includes('DÉCISION SUSPENDUE'));
assert.equal(await page.evaluate(()=>JSON.stringify(scenarioLocks[scenarioLockKey(current.id,'breakout')])),locked);
await page.getByRole('button',{name:'Garder ce scénario'}).click();
await page.screenshot({path:path.join(output,'current-scenario-390.png'),fullPage:true});results.push({test:'exact X-Perp LONG lock, stale suspension, six-horizon refresh preserves levels and favorite'});
await page.evaluate(()=>toolPage('memory'));const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Sauvegarde complète'}).click();const download=await downloadEvent;const backupPath=path.join(output,'browser-backup.json');await download.saveAs(backupPath);const backup=JSON.parse(fs.readFileSync(backupPath));assert.equal(backup.schema,'IR_BACKUP_V1');assert.ok(Object.keys(backup.data.favorites).length);
const chooserEvent=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Restaurer / importer'}).click();const chooser=await chooserEvent;await chooser.setFiles(backupPath);await page.waitForFunction(()=>importedObservationStats().total>0);assert.match(await page.locator('#deepBody').innerText(),/Historique importé — non vérifié/);assert.equal(await page.evaluate(()=>learningStats().closed),0);assert.equal(await page.evaluate(()=>JSON.stringify(scenarioLocks[scenarioLockKey(current.id,'breakout')])),locked);results.push({test:'real backup download and file import; conflict leaves local lock intact; imports not verified'});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify({results,errors},null,2));console.log(JSON.stringify({results,errors},null,2));await page.close();
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
