const {test}=require('node:test'),assert=require('node:assert/strict');const {env,frames,plain}=require('./harness.cjs');
function setup(){const e=env();e.ctx.now=Date.now();e.run("source={id:'T-USD_UM_XPERP-310101',perpId:'T-USD_UM_XPERP-310101',market:'xperp',price:102,perpPrice:102,volUsd:1e6,marketTs:now,marketFresh:true,spreadPct:.1}; model={instrumentId:source.id,analysisAt:now,triggerKey:'5m',live:102,longSetup:true,shortSetup:true,shortPattern:'rejection',directional:{longScore:70,shortScore:80},breakout:{entry:103,stop:98,tp1:108},shortRejection:{entry:100,stop:105,tp1:95},F:Object.fromEntries(DECISION_SPECS.map(([tf])=>[tf,{cs:Array(40).fill({}),c:{t:now-timeframeMs(tf)}}]))}");return e}
test('D06: shared admission rejects incomplete horizons, missing book, wrong instrument and wrong kind',()=>{const e=setup();assert.equal(e.run("admitScenario(model,source,'rejection').ok"),true);e.run('delete model.F["30m"]');assert.equal(e.run("admitScenario(model,source,'rejection').ok"),false);const f=setup();f.run("source.market='spot';source.id='T-USDT'");assert.equal(f.run("admitScenario(model,source,'rejection').ok"),false);f.run('model.instrumentId=source.id');assert.equal(f.run("admitScenario(model,source,'breakout').ok"),false);assert.equal(setup().run("admitScenario(model,source,'breakdown').ok"),false)});
test('D06: requested direction and kind never fall back to another scenario',()=>{const e=setup();assert.equal(e.run("chooseFreshScenario(model,'breakdown','short')"),null);assert.equal(e.run("chooseFreshScenario(model,'rejection','long')"),null);assert.equal(e.run("chooseFreshScenario(model,null,'long')"),'breakout')});
test('D06: scan/card/projection all use canonical depths and retain engine directional result',()=>{const e=env();e.ctx.f=frames(-.1);e.ctx.x={id:'T-USD_UM_XPERP-310101',perpId:'T-USD_UM_XPERP-310101',market:'xperp',price:82,decisionAt:1750000000000};const a=plain(e.run('candidateModel(f,x)'));e.ctx.canonical=Object.fromEntries(e.run('DECISION_SPECS').map(([tf,n])=>[tf,e.ctx.f[tf].slice(-n)]));const b=plain(e.run('candidateModel(canonical,x)'));assert.deepEqual(a,b);assert.equal(a.directional.shortScore,a.shortScore??a.directional.shortScore)});
test('D06: ranking click records exact market, direction and kind',async()=>{const e=setup();e.run("all=[{...source,sym:'T',analysisCoverage:'complete'}];detailAsync=async()=>{};refreshFavoriteButtons=()=>{}");await e.run("openDetail(source.id,'perp','short','rejection')");assert.deepEqual(plain(e.run('currentScenarioSelection')),{id:'T-USD_UM_XPERP-310101',market:'perp',direction:'short',kind:'rejection'})});
test('D06: actual ranking → scenario cards → locked projection preserve identical levels',async()=>{
 const e=env();const f=frames(.1),now=Date.now(),id='T-USD_UM_XPERP-310101';for(const [tf,bars] of Object.entries(f)){const ms=e.run(`timeframeMs('${tf}')`),end=Math.floor(now/ms)*ms;bars.forEach((b,i)=>b.t=end-(bars.length-1-i)*ms)}
 e.ctx.f=f;e.ctx.x={id,perpId:id,sym:'T',market:'xperp',price:f['5m'].at(-2).c,volUsd:1e6,vol:1e6,medVol:1e6,marketFresh:true,marketTs:now,spreadPct:.1};
 e.ctx.candles=async(inst,tf,n)=>{assert.equal(inst,id);return f[tf].slice(-n)};e.ctx.get=async p=>p.includes('/instruments')?[{instId:id,ruleType:'xperp',state:'live'}]:[{last:String(e.ctx.x.price),bidPx:String(e.ctx.x.price*.9995),askPx:String(e.ctx.x.price*1.0005),ts:String(Date.now())}];
 e.run('current=x;all=[x];x.scenarioModel=candidateModel(f,x);x.directional=x.scenarioModel.directional;bindScenarioSim=()=>{}');const candidate=e.run('scenarioCandidates()[0]');assert.equal(candidate.kind,'breakout');const expected=plain(e.run('x.scenarioModel.breakout'));
 e.run("currentScenarioSelection={id:current.id,market:'perp',direction:'long',kind:'breakout'}");const html=await e.run('scenarioHtml()');assert.match(html,/Ouvrir la projection/);assert.doesNotMatch(html,/Rejet conditionnel de résistance/);
 await e.run("openScenarioMonitor(current.id,'breakout')");const lock=plain(e.run("scenarioLocks[scenarioLockKey(current.id,'breakout')]"));for(const k of ['entry','stop','tp1','tp2','tp3'])assert.equal(lock[k],expected[k]);assert.equal(lock.instrumentId,id);assert.equal(lock.direction,'long');e.run('stopScenarioUpdates()');
});
test('D06: existing Spot lock cannot activate with missing depth or excessive spread',async()=>{
 for(const missingBook of [true,false]){
  const e=env(),f=frames(.1),now=Date.now();for(const [tf,bars] of Object.entries(f)){const ms=e.run(`timeframeMs('${tf}')`),end=Math.floor(now/ms)*ms;bars.forEach((b,i)=>b.t=end-(bars.length-1-i)*ms);bars.at(-2).v=1e6}
  e.ctx.f=f;e.ctx.candles=async(id,tf,n)=>f[tf].slice(-n);const price=f['5m'].at(-2).c;
  e.ctx.get=async path=>{if(path.includes('/books')){if(missingBook)throw Error('no depth');return [{ts:String(Date.now()),bids:[[String(price-.01),'10000']],asks:[[String(price+.01),'10000']]}]}return [{last:String(price),bidPx:String(price*(missingBook?.9995:.9)),askPx:String(price*(missingBook?1.0005:1.1)),ts:String(Date.now())}]};
  e.ctx.price=price;e.run("current={id:'T-USDT',sym:'T',market:'spot',price,volUsd:1e6};scenarioMonitorFrames=f;scenarioMonitorAnalysisAt=Date.now();scenarioMonitorKind='breakout';scenarioMonitorBar='5m';scenarioLocks['T-USDT::breakout']={id:'existing',kind:'breakout',direction:'long',instrumentId:'T-USDT',triggerKey:'5m',entry:price-.1,stop:price-5,tp1:price+5,tp2:price+10,tp3:price+15};scenarioBiasCompatible=()=>true;bindScenarioSim=()=>{};journalAdvance=(lock,side,bars,activated,ms,now,available)=>{activationAttempt={activated,available};return {status:'FORMING'}}");
  const before=e.run('JSON.stringify(scenarioLocks)');await e.run("renderScenarioMonitor('breakout',false)");assert.equal(e.run('activationAttempt.activated'),false);assert.equal(e.run('activationAttempt.available'),false);assert.match(e.node('deepBody').innerHTML,/DÉCISION SUSPENDUE/);assert.equal(e.run('JSON.stringify(scenarioLocks)'),before);
 }
});
