const {test}=require('node:test'),assert=require('node:assert/strict');const {env}=require('./harness.cjs');
test('D03: rejection against major bias uses its admitted pattern, not global biasBear',()=>{const {run}=env();assert.equal(run("scenarioBiasCompatible({biasBear:false,shortSetup:true,shortPattern:'rejection'},'rejection')"),true);assert.equal(run("scenarioBiasCompatible({biasBear:true,shortSetup:true,shortPattern:'rejection'},'breakdown')"),false);assert.equal(run("scenarioBiasCompatible({biasBull:true},'breakout')"),true)});
test('D04: live stop alert is provisional, not a resolved observation',()=>{const {run}=env();const v=run("monitorTriggerStatus({invalid:true,stop:95})");assert.equal(v.state,'yellow');assert.match(v.label,/PROVISOIRE/)});
function setup(createdAt=0){const e=env();e.ctx.lock={id:'x',entry:100,stop:95,tp1:105};e.store.set('ir_learning_journal_v866',JSON.stringify([{id:'x',status:'FORMING',createdAt}]));return e}
const bar=(t,h,l,c=99)=>({t,o:99,h,l,c,v:100,confirm:1});
test('D04: after interruption a possible old activation must be UNVERIFIED',()=>{const e=setup();e.ctx.bars=[bar(0,103,98,102),bar(300000,106,94,99)];assert.equal(e.run("journalAdvance(lock,'long',bars,true,300000,600000).status"),'UNVERIFIED')});
test('D04: known untriggered bars replay stop wick even if close recovers',()=>{const e=setup();e.ctx.bars=[bar(0,99,98),bar(300000,99,94,98),bar(600000,99,97)];assert.equal(e.run("journalAdvance(lock,'long',bars,false,300000,900000).status"),'CANCELLED')});
test('D04: same bar entry/stop and missing prefix cannot be declared cancelled or activated',()=>{for(const bars of [[bar(0,102,94,101)],[bar(900000,103,98,102)]]){const e=setup();e.ctx.bars=bars;assert.equal(e.run("journalAdvance(lock,'long',bars,true,300000,1200000).status"),'UNVERIFIED')}});
test('D04: uninterrupted entry, next-bar exit, idempotence',()=>{const e=setup();e.ctx.bars=[bar(0,99,98)];assert.equal(e.run("journalAdvance(lock,'long',bars,false,300000,300000).status"),'FORMING');e.ctx.bars.push(bar(300000,103,98,102));assert.equal(e.run("journalAdvance(lock,'long',bars,true,300000,600000).status"),'ACTIVATED');e.ctx.bars.push(bar(600000,106,94));assert.equal(e.run("journalAdvance(lock,'long',bars,false,300000,900000).outcome.status"),'SL');assert.equal(e.run("journalAdvance(lock,'long',bars,false,300000,900000).outcome.status"),'SL')});
